# 빌드 스테이지
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_GITLAB_URL
ARG VITE_GITLAB_TOKEN
ARG VITE_REDMINE_URL
ARG VITE_REDMINE_API_KEY
ARG VITE_ANTHROPIC_API_KEY
ARG VITE_CLAUDE_MODEL=claude-haiku-4-5
ARG VITE_DEFAULT_REFRESH_INTERVAL=900

ENV VITE_GITLAB_URL=$VITE_GITLAB_URL
ENV VITE_GITLAB_TOKEN=$VITE_GITLAB_TOKEN
ENV VITE_REDMINE_URL=$VITE_REDMINE_URL
ENV VITE_REDMINE_API_KEY=$VITE_REDMINE_API_KEY
ENV VITE_ANTHROPIC_API_KEY=$VITE_ANTHROPIC_API_KEY
ENV VITE_CLAUDE_MODEL=$VITE_CLAUDE_MODEL
ENV VITE_DEFAULT_REFRESH_INTERVAL=$VITE_DEFAULT_REFRESH_INTERVAL

RUN npm run build

# 프로덕션 스테이지
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
